// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gamzpjgqugpzquykpmpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhbXpwamdxdWdwenF1eWtwbXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzYxOTQsImV4cCI6MjA3Mzc1MjE5NH0._xTDLSJaydSgFFk3icF30Mvhqce78wbYAmyzN3pZZFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});